name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - 'Emitron/.swiftlint.yml'
      - 'Emitron/**/*.swift'

jobs:
  SwiftLint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1

      - name: Run Swiftlint
        run: swiftlint --config Emitron/.swiftlint.yml
